spring:
  kafka:
    bootstrap-servers: localhost:29092
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/statistics?authSource=admin

app:
  kafka:
    group-id: "hotel-group-id"
  statistics:
    download-folder: "download/"

server:
  port: 8081
