spring:
  kafka:
    bootstrap-servers: localhost:9092
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/statistics?authSource=admin

app:
  kafka:
    group-id: "hotel-group-id"

server:
  port: 8081
