spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/app_db
    username: postgres
    password: postgres
    hikari:
      schema: app_schema
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS app_schema
      connection-timeout: 10000
  kafka:
    bootstrap-servers: localhost:9092

app:
  global-exception-handler:
    enable: true
  kafka:
    group-id: "hotel-group-id"
